### ISSUE TITLE
更换主题后生成的index是空白的

### ISSUE THREAD

**Issue by blackw4tch** [MSC-XDU/Hexo-learn-document#11]
换了一个主题之后hexo clean+hexo generate+hexo s本地查看是空白页面，public里面的index.html打开也是空白的，是怎么回事呢？（config里面已经修改了）

**Comment by blackw4tch** [comment]
报错如下：WARN  No layout: index.html

**Comment by yrpang** [comment]
你用的是什么主题？另外我觉得大概率是你把配置里的主题名称写错了，名称应该和themes文件夹下你的主题文件夹名称一致

**Comment by blackw4tch** [comment]
我考虑到了，不是这个问题，配置里面我反复检查过，我用next和chic都试了，同样的问题

**Comment by yrpang** [comment]
你得提供更多信息，不然我也猜不到是哪里出了问题emm:
1. hexo g的完整输出
2. 你博客配置文件
3. 你的主题配置文件
4. 你的themes目录下面的内容截图

**Comment by blackw4tch** [comment]
![QQ截图20200229130019](https://user-images.githubusercontent.com/55129687/75601178-ad580100-5af3-11ea-83ab-80378ac28c4b.png)
![QQ截图20200229125953](https://user-images.githubusercontent.com/55129687/75601181-b052f180-5af3-11ea-94de-ff834c60ee2a.png)
![(J8DS`XFQF$7}{R~62 LHU8](https://user-images.githubusercontent.com/55129687/75601185-b3e67880-5af3-11ea-8de9-18febfbeadd0.png)
![`N@0% ${HR {V0T}58Q_EZB](https://user-images.githubusercontent.com/55129687/75601187-b648d280-5af3-11ea-8a4a-92ba07f7910f.png)
