### ISSUE TITLE
添加rss失败

### ISSUE THREAD

**Issue by Alpha-Yang** [MSC-XDU/Hexo-learn-document#12]
在blog目录下，安装插件：npm install hexo-generator-feed
显示一群warning
并且有一句话看不懂
+ hexo-generator-feed@2.2.0
removed 317 packages, updated 1 package and audited 4926 packages in 7.005s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by yrpang** [comment]
提交上来的这部分没有任何问题
```
hexo-generator-feed@2.2.0
removed 317 packages, updated 1 package and audited 4926 packages in 7.005s
```
这部分是一个安装结果的报告
后面是有一些包的开发者在接受资金支持。世界是很真实的，谁也不能靠喝西北风活着，开源开发者也是一样，所以开发者可以在发布自己包的时候把收款信息也发布出来，`npm`会在你安装它们的时候提示你有哪些包在`looking for funding`，以帮助他们获得更多资金支持。
此外GitHub也有类似的功能 [GitHub Sponsors](https://github.com/sponsors/)
