### ISSUE TITLE
commit迷惑问题

### ISSUE THREAD

**Issue by Alpha-Yang** [MSC-XDU/Hexo-learn-document#13]
添加博客地址的时候
明明修改了readme和feeds
但是git commit的时候告诉我
no change

**Comment by Warmchay** [comment]
1. git add .      
2.   git commit -m "address"
3.   git push -u origin master

**Comment by yrpang** [comment]
@Warmchay 的回复应该可以解决你的问题，不过有一点可能需要说明
在3中并不需要每次都使用`-u`选项，它用于第一次将本地仓库推送到远程时建立关联
摘录帮助中关于`-u`的说明如下，更多内容参见`git help push` 以及`git help`
```
-u, --set-upstream
           For every branch that is up to date or successfully pushed, add
           upstream (tracking) reference, used by argument-less git-pull(1)
           and other commands. For more information, see branch.<name>.merge
           in git-config(1).
```
