### ISSUE TITLE
碰到的几个小问题（还会更新——

### ISSUE THREAD

**Issue by HankZhangZ** [MSC-XDU/Hexo-learn-document#2]
好的在某人多次提醒下我来写一下建站时候遇到的问题（可能只有我遇到了  毕竟菜死

0.Windows下的命令行（建议自行百度  我就是标准丢人例子）

1.新建的仓库名称必须和个人名称（username）一样！！
    要不然会疯狂404...

2.每次改完东西要重新生成（别骂了我知道只有我不知道）
    hexo d之后有延迟emmm要等一会的

3.善用官方文档
    https://hexo.io/zh-cn/docs/templates
    https://hexo.io/zh-cn/docs/writing#%E6%A8%A1%E7%89%88%EF%BC%88Scaffold%EF%BC%89  （这个是关于文档模板的）

4.庞人语录：
    “不管是什么文档 里面的[] <>类似这样子的内容 意思都是把这个替换成相应的真实内容”
    “补充第二条原则 如果你在已有配置文件基础上改动的话参照原来配置文件的样子写”

tips.建议用SSH

**Comment by yrpang** [comment]
超级感谢 emmmm（语录是什么鬼emmmm （逃

**Comment by yrpang** [comment]
对应上面问题

1. `Github Page`有两种 我们这里用到的是个人主页所以要遵照这个命名格式
更多介绍和内容参见[官方文档](https://help.github.com/cn/github/working-with-github-pages)
及[官方介绍页](https://pages.github.com/)

4. 我觉得这两条还挺真实且有用的其实emmmm （逃
