### ISSUE TITLE
npm下载过慢及换源相关问题

### ISSUE THREAD

**Issue by AlexanderDemetrius** [MSC-XDU/Hexo-learn-document#4]
1.nodejs下载后安装在C盘。（为了省几十mb空间硬是被我搬到D盘，又推倒重来orz）。
2.git工具（官网https://git-scm.com/download/win）搭梯子后下载更快（也许（试了三四次。
（3.cmd打开：windows键+R后输入cmd，回车（废话））。
3.由于国内npm安装可能有问题，另提供cnpm的安装，但是两者只需其一，如果npm版本查看无误则无需cnpm。
4.npm（或者cnpm）确认安装无误后需输入：
npm（或者cnpm）（空格）install -g hexo-cli --registry=https://registry.npm.taobao.org
如果出现error，注意空格，注 意 空 格，注  意  空  格！
以上

**Comment by yrpang** [comment]
(建议把报错图片也发出来
或者粘贴上报错内容
```
error code .....
```

**Comment by AlexanderDemetrius** [comment]
报错![疯狂报错](https://user-images.githubusercontent.com/61503877/75358913-93010600-58ee-11ea-95c0-d9d1c83e1f92.JPG)

**Comment by AlexanderDemetrius** [comment]
未换源![未换源](https://user-images.githubusercontent.com/61503877/75358992-af04a780-58ee-11ea-836c-281f10b479fd.JPG)

**Comment by AlexanderDemetrius** [comment]
hexo安装成功
![hexo安装成功](https://user-images.githubusercontent.com/61503877/75359100-da879200-58ee-11ea-95bc-972892ae9a18.JPG)

**Comment by yrpang** [comment]
关于上面的问题：
1. 主要占地方并且会随着你`npm install -g` 的东西越来越多而不断变大的是`node_modules`这或许是你更应该担心的问题，摘录部分`manual`供参考，具体适用于`Windows`的情况请自行查阅文档

```
   Directories
       See npm help folders to learn about where npm puts stuff.

       In particular, npm has two modes of operation:

       o global mode: npm installs packages into the install  prefix  at  pre-
         fix/lib/node_modules and bins are installed in prefix/bin.

       o local mode: npm installs packages into the current project directory,
         which defaults  to  the  current  working  directory.   Packages  are
         installed  to  ./node_modules,  and bins are installed to ./node_mod-
         ules/.bin.

```
2. 如果你熟悉Linux的话那个`git bash`可能用起来更顺手

3. 关于`cnpm`说明在这里，他只是改动一点儿配置的`npm`而已

4. 不仅是这个指令 在输入一切指令的时候都请注意这一点

**Comment by yrpang** [comment]
一些附注：
`GitHub issue`在发出后是可以编辑的，如果需要修改自己发出的内容 请使用编辑。因为每次在下面添加内容都会给subscribe了这个issue的人发送一份邮件…

<img width="263" alt="截屏2020-02-26下午11 30 08" src="https://user-images.githubusercontent.com/7457280/75359886-fc354900-58ef-11ea-9ddf-e745f9c6f2fa.png">
