### ISSUE TITLE
hexo无法部署

### ISSUE THREAD

**Issue by AlexanderDemetrius** [MSC-XDU/Hexo-learn-document#7]
在config.yaml文件更改deployment内容之后hexo无法部署到远端
![改](https://user-images.githubusercontent.com/61503877/75412144-89ae8280-595c-11ea-9347-71aa0b5c3a14.png)

cmd命令hexo d之后

error deployer not found：git
![error](https://user-images.githubusercontent.com/61503877/75412151-903cfa00-595c-11ea-9726-070611dde285.png)

**Comment by yrpang** [comment]
需要安装`hexo-deployer-git` 使用`npm install hexo-deployer-git --save`安装即可

查看官方文档说了这是怎么工作的，另外hexo也支持部署到其它地方，文档里也有说明

文档：[https://hexo.io/zh-cn/docs/one-command-deployment](https://hexo.io/zh-cn/docs/one-command-deployment)

**Comment by AlexanderDemetrius** [comment]
问题已解决，谢谢

**Comment by yrpang** [comment]
👌
